// ============================================================
// PDF Report Generator
// ============================================================
// Generates a downloadable PDF from the analysis data.
// Uses jsPDF for PDF creation with a clean, professional layout.
// ============================================================

import jsPDF from 'jspdf';

/**
 * Generates and downloads a PDF report for the analysis.
 * @param {object} data - The analysis data object
 */
export function generatePDFReport(data) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  // ── Header ──────────────────────────────────
  doc.setFontSize(24);
  doc.setTextColor(59, 130, 246);
  doc.text('InvestIQ AI', pageWidth / 2, y, { align: 'center' });
  y += 10;

  doc.setFontSize(12);
  doc.setTextColor(150, 150, 150);
  doc.text('Investment Research Report', pageWidth / 2, y, { align: 'center' });
  y += 15;

  // ── Company Name ────────────────────────────
  doc.setFontSize(20);
  doc.setTextColor(30, 30, 30);
  doc.text(`${data.company} (${data.ticker})`, pageWidth / 2, y, { align: 'center' });
  y += 12;

  // ── Recommendation ──────────────────────────
  const recColor = data.recommendation === 'INVEST' ? [16, 185, 129] : [239, 68, 68];
  doc.setFontSize(16);
  doc.setTextColor(...recColor);
  doc.text(`Recommendation: ${data.recommendation}`, pageWidth / 2, y, { align: 'center' });
  y += 15;

  // ── Scores ──────────────────────────────────
  doc.setFontSize(11);
  doc.setTextColor(60, 60, 60);

  const scores = [
    ['Overall Score', `${data.overallScore}/100`],
    ['Confidence', `${data.confidence}%`],
    ['Risk Level', data.risk],
    ['Financial Health', `${data.financialHealth}/100`],
    ['Growth', `${data.growth}/100`],
    ['Market Position', `${data.marketPosition}/100`],
    ['Innovation', `${data.innovation}/100`],
  ];

  scores.forEach(([label, value]) => {
    doc.setFont(undefined, 'bold');
    doc.text(`${label}:`, 20, y);
    doc.setFont(undefined, 'normal');
    doc.text(value, 80, y);
    y += 7;
  });

  y += 5;

  // ── Summary ─────────────────────────────────
  doc.setFontSize(14);
  doc.setFont(undefined, 'bold');
  doc.setTextColor(30, 30, 30);
  doc.text('Summary', 20, y);
  y += 8;

  doc.setFontSize(10);
  doc.setFont(undefined, 'normal');
  doc.setTextColor(60, 60, 60);
  const summaryLines = doc.splitTextToSize(data.summary, pageWidth - 40);
  doc.text(summaryLines, 20, y);
  y += summaryLines.length * 5 + 8;

  // ── Pros ────────────────────────────────────
  doc.setFontSize(14);
  doc.setFont(undefined, 'bold');
  doc.setTextColor(16, 185, 129);
  doc.text('Pros', 20, y);
  y += 8;

  doc.setFontSize(10);
  doc.setFont(undefined, 'normal');
  doc.setTextColor(60, 60, 60);
  data.pros.forEach((pro) => {
    doc.text(`✓  ${pro}`, 25, y);
    y += 6;
  });
  y += 5;

  // ── Cons ────────────────────────────────────
  doc.setFontSize(14);
  doc.setFont(undefined, 'bold');
  doc.setTextColor(239, 68, 68);
  doc.text('Cons', 20, y);
  y += 8;

  doc.setFontSize(10);
  doc.setFont(undefined, 'normal');
  doc.setTextColor(60, 60, 60);
  data.cons.forEach((con) => {
    doc.text(`✗  ${con}`, 25, y);
    y += 6;
  });
  y += 5;

  // ── Check if we need a new page ─────────────
  if (y > 240) {
    doc.addPage();
    y = 20;
  }

  // ── Explanation ─────────────────────────────
  doc.setFontSize(14);
  doc.setFont(undefined, 'bold');
  doc.setTextColor(30, 30, 30);
  doc.text('Analysis', 20, y);
  y += 8;

  doc.setFontSize(10);
  doc.setFont(undefined, 'normal');
  doc.setTextColor(60, 60, 60);
  const expLines = doc.splitTextToSize(data.explanation, pageWidth - 40);
  doc.text(expLines, 20, y);
  y += expLines.length * 5 + 10;

  // ── Footer ──────────────────────────────────
  const footerY = doc.internal.pageSize.getHeight() - 15;
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(
    `Generated by InvestIQ AI on ${new Date().toLocaleDateString()} — For educational purposes only`,
    pageWidth / 2,
    footerY,
    { align: 'center' }
  );

  // Download the PDF
  doc.save(`InvestIQ_${data.company.replace(/\s+/g, '_')}_Report.pdf`);
}
