// ============================================================
// Report Actions Component
// ============================================================
// Action buttons for Copy, Download PDF, and Share report.
// ============================================================

import { useState } from 'react';
import { motion } from 'framer-motion';
import { HiOutlineClipboardCopy, HiOutlineDownload, HiOutlineShare } from 'react-icons/hi';
import { generatePDFReport } from '../utils/pdfGenerator';
import { useTheme } from '../hooks/useTheme';

export default function ReportActions({ data }) {
  const [copied, setCopied] = useState(false);
  const [shared, setShared] = useState(false);
  const { theme } = useTheme();

  // Copy report as formatted text to clipboard
  const handleCopy = async () => {
    const reportText = `
InvestIQ AI — Investment Report
================================
Company: ${data.company}
Recommendation: ${data.recommendation}
Overall Score: ${data.overallScore}/100
Confidence: ${data.confidence}%
Risk: ${data.risk}

Summary: ${data.summary}

Financial Health: ${data.financialHealth}/100
Growth: ${data.growth}/100
Market Position: ${data.marketPosition}/100
Innovation: ${data.innovation}/100

Pros:
${data.pros.map((p) => `  ✓ ${p}`).join('\n')}

Cons:
${data.cons.map((c) => `  ✗ ${c}`).join('\n')}

Analysis: ${data.explanation}

Simple Explanation: ${data.beginnerExplanation}
================================
Generated by InvestIQ AI
    `.trim();

    await navigator.clipboard.writeText(reportText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  // Download PDF report
  const handleDownload = () => {
    generatePDFReport(data);
  };

  // Share via Web Share API or fallback to copy
  const handleShare = async () => {
    const shareData = {
      title: `InvestIQ AI — ${data.company} Analysis`,
      text: `${data.company}: ${data.recommendation} (Score: ${data.overallScore}/100, Confidence: ${data.confidence}%)`,
      url: window.location.href,
    };

    if (navigator.share) {
      try {
        await navigator.share(shareData);
      } catch {
        // User cancelled share
      }
    } else {
      // Fallback: copy share text to clipboard
      await navigator.clipboard.writeText(
        `${shareData.title}\n${shareData.text}\n${shareData.url}`
      );
      setShared(true);
      setTimeout(() => setShared(false), 2000);
    }
  };

  const buttonClass = `flex items-center gap-2 px-4 py-2.5 text-sm font-medium rounded-xl border transition-all duration-300 ${
    theme === 'dark'
      ? 'bg-white/5 border-white/10 text-gray-300 hover:bg-white/10'
      : 'bg-white border-gray-200 text-gray-700 hover:bg-gray-100'
  }`;

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: 0.9 }}
      className="flex flex-wrap gap-3"
    >
      <motion.button
        whileHover={{ scale: 1.02 }}
        whileTap={{ scale: 0.98 }}
        onClick={handleCopy}
        className={buttonClass}
      >
        <HiOutlineClipboardCopy />
        {copied ? '✓ Copied!' : 'Copy Report'}
      </motion.button>

      <motion.button
        whileHover={{ scale: 1.02 }}
        whileTap={{ scale: 0.98 }}
        onClick={handleDownload}
        className={buttonClass}
      >
        <HiOutlineDownload />
        Download PDF
      </motion.button>

      <motion.button
        whileHover={{ scale: 1.02 }}
        whileTap={{ scale: 0.98 }}
        onClick={handleShare}
        className={buttonClass}
      >
        <HiOutlineShare />
        {shared ? '✓ Link Copied!' : 'Share'}
      </motion.button>
    </motion.div>
  );
}
